export const GET_COMMENT_START = "GET_COMMENT_START";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_ALL_COMMENT_SUCCESS = "GET_ALL_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";
